### ISSUE TITLE
Wrap long lines to prevent mobile layout breaking

### ISSUE THREAD

**Issue by andylolz** [codeforIATI/codelists#56]
![Screenshot 2020-02-10 at 10 32 10](https://user-images.githubusercontent.com/464193/74142362-9d35bb80-4bf0-11ea-9f36-84883b3e0909.png)

I think we need something like this:

```css
body {
  overflow-wrap: break-word;
}
```
